BasketballAcademyBlog/Models/Publication.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BasketballAcademyBlog.Models
{
    public class Publication
    {
        //
        // Primary Key of the Table "Publications" in database
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }
        
        public DateTime DateTime { get; set; }
        
        public string Link { get; set; }

        [ForeignKey("Author")]
        public string AuthorId { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }

        public virtual ApplicationUser Author { get; set; }

    }
}

BasketballAcademyBlog/Controllers/PublicationController.cs
using BasketballAcademyBlog.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BasketballAcademyBlog.Controllers
{
    public class PublicationController : Controller
    {
        // GET: Publication
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        // GET Publication/List
        public ActionResult List()
        {
            using (var database = new BlogDbContext())
            {
                var publications = database
                    .Publications
                    .Include(p => p.Author)
                    .ToList();

                return View(publications);
            }
        }

        //
        //GET Publication/ReadPost
        public ActionResult ReadPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                var publication = database
                    .Publications
                    .Where(p => p.Id == id)
                    .Include(p => p.Author)
                    .Include(p => p.Comments)
                    .First();

                if (publication == null)
                {
                    return HttpNotFound();
                }

                return View(publication);
            }
        }

        //GET Publication/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        //POST Publication/Create      
        [HttpPost]
        [Authorize]
        public ActionResult Create(Publication publication)
        {
            if (ModelState.IsValid)
            {
                using (var database = new BlogDbContext())
                {
                    var authorId = database
                        .Users
                        .Where(u => u.UserName == this.User.Identity.Name)
                        .First()
                        .Id;
                    publication.AuthorId = authorId;
                    publication.DateTime = DateTime.Now;

                    database.Publications.Add(publication);
                    database.SaveChanges();
                    return RedirectToAction("List");
                }
            }
            return View(publication);
        }

        //GET: Publication/Delete
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                var publication = database.Publications
                    .Where(p => p.Id == id)
                    .Include(a => a.Author)
                    .Include(p => p.Comments)
                    .First();

                if (publication == null)
                {
                    return HttpNotFound();
                }
                return View(publication);
            }
        }


        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var database = new BlogDbContext())
            {
                var publication = database.Publications
                    .Where(p => p.Id == id)
                    .Include(p => p.Author)
                    .Include(p => p.Comments)
                    .First();

                if (publication == null)
                {
                    return HttpNotFound();
                }

                database.Publications.Remove(publication);
                database.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Comment ([Bind(Include ="postID, name, message")] int postID, string name, string message)
        {
            var database = new BlogDbContext();
            Publication publication = database.Publications.Find(postID);
            Comment comment = new Comment();
            comment.postID = postID;
            comment.Email = User.Identity.Name;
            comment.CreatedDate = DateTime.Now;
            comment.Name = User.Identity.Name;
            comment.Body = message;
            comment.Publication = publication;

            database.Comments.Add(comment);
            database.SaveChanges();
            return RedirectToAction("");
        }

        [Authorize]
        public ActionResult DeleteComment (int id)
        {
            using (var database = new BlogDbContext())
            {
                Comment comment = database.Comments.Find(id);
                if(comment ==null)
                {
                    return HttpNotFound();
                }
                database.Comments.Remove(comment);
                database.SaveChanges();

                return RedirectToAction("");
            }
        }
    }
}

BasketballAcademyBlog/Views/Publication/Create.cshtml
@model BasketballAcademyBlog.Models.Publication
@{
    ViewBag.Title = "Create";
}

<div class="container">
        <h2>Create Post</h2>
        @using (Html.BeginForm("Create", "Publication", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Link, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Link, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "Index", "Publication", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Create Post" class="btn btn-success" />
                </div>
            </div>
        }
</div>

BasketballAcademyBlog/Views/Publication/Delete.cshtml
@model BasketballAcademyBlog.Models.Publication

@{
    ViewBag.Title = "Delete";
}

<div class="container">
        <h2>Delete Post</h2>
        @using (Html.BeginForm("Delete", "Publication", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @readonly = "readonly", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    @Html.ActionLink("Cancel", "Index", "Publication", null, new { @class = "btn btn-default" })
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>
        }
</div>

BasketballAcademyBlog/Views/Publication/List.cshtml
@model List<BasketballAcademyBlog.Models.Publication>

@{
    ViewBag.Title = "List";
}
<div class="container">
    <div class="row">
        @foreach (var publication in Model)
        {
            <article class="col-sm-6">
                <header>
                    <h2>
                        <img src="~/Content/images/icon.png" width="45" height="60" />
                        @Html.ActionLink(@publication.Title, "ReadPost", "Publication", new { @id = publication.Id }, null)
                    </h2>
                </header>
                <p>
                    @publication.Content.Substring(0, @publication.Content.Length/3)...
                    @Html.ActionLink("Read more", "ReadPost", "Publication", new { @id = publication.Id }, null)
                </p>
                <footer>
                    <small class="author">
                        Posted by @publication.Author.FullName
                        <br>
                        On Date: @publication.DateTime
                    </small>
                </footer>
            </article>
        }
    </div>
</div>
       

BasketballAcademyBlog/Views/Publication/ReadPost.cshtml
@model BasketballAcademyBlog.Models.Publication

@{
    ViewBag.Title = "ReadPost";
}

<div class="container">
    <div class="row">
        <article class="col-sm-4">
            <header>
                <h2>
                    @Model.Title
                </h2>
            </header>
            <p>
                @Model.Content
            </p>
            <small class="author">
                Posted by @Model.Author.FullName
                <br>
                Date: @Model.DateTime
            </small>
            <footer class="pull-right">
                @if (User.IsInRole("Admin"))
            {
                    @Html.ActionLink("Delete", "Delete", "Publication", new { @id = Model.Id }, new { @class = "btn btn-danger btn-xs" })
                }
                @Html.ActionLink("Back", "Index", "Publication", null, new { @class = "btn btn-default btn-xs" })
            </footer>
        </article>

        <div class="col-sm-6">
            @if (User.Identity.IsAuthenticated)
            {
                <iframe width="560"
                        height="315"
                        src="@Model.Link"
                        frameborder="0"
                        allowfullscreen></iframe>
            }
            else
            {
                <hr />
                <p class="alert-dismissible">
                    @Html.ActionLink("LOG IN", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
                    OR 
                    @Html.ActionLink("REGISTER", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })
                    <br> FOR REACHING WHOLE RESOURCES IN THIS POST
                </p>
                <hr/>
            }
        </div>
    </div>

    <div class="col-md-12">
        @if (Model.Comments.Count != 0)
        {
            <h4>Comments:</h4>
            <div class="blog-post-comments">
                @foreach (var comment in Model.Comments.OrderBy(x => x.CreatedDate))
                {
                    <blockquote>
                        <h4 class="comment-caption text-info">@comment.Name</h4>
                        <p>@Html.Encode(comment.Body)</p>
                        <small>@comment.CreatedDate</small>
                        @if (comment.isAuthor(User.Identity.Name, comment) || User.IsInRole("Admin"))
                        {
                            @Html.ActionLink("Delete comment", "DeleteComment", new { id = comment.ID }, new { @class = "text-danger" })
                        }
                    </blockquote>
                }
            </div>
        }
        @if (User.Identity.IsAuthenticated)
        {
            <div class="comment-editor">
                @using (Html.BeginForm("Comment", "Publication", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Add Comment</h4>
                        @User.Identity.Name
                        <input type="hidden" value="@Model.Id" name="postID" />
                        <div class="form-group">
                            <div class="col-sm-6">
                                <textarea class="form-control text-box multi-line" id="Message" name="Message" rows="3"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-6">
                                <input type="submit" value="Submit" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
    </div>
</div>